services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab  
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'  
        gitlab_rails['initial_root_password'] = 'password'  
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config.toml:/etc/gitlab-runner/config.toml
      # - gitlab-runner-config:/etc/gitlab-runner
    environment:
      - CI_SERVER_URL=http://gitlab 
      - REGISTRATION_TOKEN=<you-token-here>
      - RUNNER_NAME=my-runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=alpine:latest
    networks:
      - gitlab-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  # gitlab-runner-config:

networks:
  gitlab-network:
